export { default as AboutPage } from './About'
export { default as SignInPage } from './SignIn'
export { default as SignUpPage } from './SignUp'
export { default as ProfilePage } from './Profile'
export { default as HomePage } from './Home'
