export { default as About } from './About'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Profile } from './Profile'
export { default as Home } from './Home'
